[package]
name = "hanzi4096"
version = "0.1.0"
authors = ["quininer kel <quininer@live.com>"]
build = "build.rs"

[dependencies]
lazy_static = "0.2"

[dev-dependencies]
clap = "2.20"
quickcheck = "0.4"
